# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.5

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        run: |
          go test -v -cover
